- id: jsonschema
  name: jsonschema
  description: json schema validation
  language: python
  pass_filenames: false
  entry: jsonschema

- id: validate
  name: jsonschema validate
  description: json schema validation
  entry: python -m jsonschema._pre_commit_cli
  language: python
  files: ^$
