#! /usr/bin/env python
"""
A *very* basic performance test.

"""

from __future__ import print_function
import argparse
import textwrap
import timeit

parser = argparse.ArgumentParser()
parser.add_argument("-n", "--number", type=int, default=100)
arguments = parser.parse_args()

results = timeit.timeit(
    number=arguments.number,
    # Validate the Draft 3 meta-schema against itself without meta-validating
    stmt="validate(instance, schema)",
    setup=textwrap.dedent("""
    from jsonschema import Draft3Validator, validate
    instance = schema = Draft3Validator.META_SCHEMA
    """),
)

print(
    "Validated %s times. Finished in %s seconds." % (arguments.number, results)
)
